Djago Website-/djangoWebsite/apps/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
app_name="accounts"
urlpatterns = [
    path('profile', views.ProfileView.as_view(), name="profile"),

    #path('',TemplateView.as_view(template_name ='index.html'), name="index")

    #django authentication
    #accounts/login is one of the 8 django_auth configurations should be placed in as_views
    path('login', auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path('logout', auth_views.LogoutView.as_view(), name="logout"),

]

Djago Website-/djangoWebsite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("hackershack_website.apps.public.urls")),
    path("accounts/", include("hackershack_website.apps.accounts.urls")),
    path("contact/", include("hackershack_website.apps.contact.urls")),
]

Djago Website-/djangoWebsite/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class UserInterest(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class UserPersona(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    # owner
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")

    # settings
    is_full_name_displayed = models.BooleanField(default=True)

    # details
    bio = models.CharField(max_length=500, blank=True, null=True)
    website = models.URLField(max_length=200, blank=True, null=True)
    persona = models.ForeignKey(
        UserPersona, on_delete=models.SET_NULL, blank=True, null=True
    )
    interests = models.ManyToManyField(UserInterest, blank=True)

Djago Website-/djangoWebsite/apps/accounts/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

Djago Website-/djangoWebsite/views.py
#from django.http import HttpResponse
#from django.template import loader
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

Djago Website-/djangoWebsite/templates/about.html
{% extends 'base.html' %}
{% block title %}Template Home {% endblock %}}
{% block content %}
<h1>
    About
</h1>
    
{% endblock %}

Djago Website-/djangoWebsite/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}Template Home {% endblock %}}
{% block content %}
<h2>Login</h2>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Login</button>

</form>
    
{% endblock %}

Djago Website-/djangoWebsite/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}

<h1>
    {{ user.get_full_name }} (@{{user.username}})
</h1>

{% with profile=user.profile %}
    {% if profile %}
        <h2>
            {{ profile.persona|default:"" }}
        </h2>
        <div>
            {{ profile.bio|default:"" }}
        </div>
        <div>
            {% with website=profile.website|default:"" %}
                <a href="{{website}}">{{ website }}</a>
            {% endwith %}
        </div>
        <br/>
        <div>
            Interests:
            {% for interest in profile.interests.all %}
                <span>
                    {{ interest.name }}{% if not forloop.last %}, {% endif %}
                </span>
            {% endfor %}
        </div>
    {% endif %}
{% endwith %}


{% endblock %}

Djago Website-/djangoWebsite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Hacker Shank {% endblock %}}</title>
</head>
<body>
    {% include 'navbar.html'%}
    <main>
        {% block content %}
        {% endblock %}
    </main>
    
</body>
</html>

Djago Website-/djangoWebsite/templates/contact.html
{% extends 'base.html' %}
{% block title %}Template Home {% endblock %}}
{% block content %}
<h1>
    Contact
</h1>
    
{% endblock %}

Djago Website-/djangoWebsite/templates/index.html
{% extends 'base.html' %}
{% block title %}Template Home {% endblock %}}
{% block content %}
<h1>
    Template Homepage
</h1>
    
{% endblock %}

Djago Website-/djangoWebsite/templates/navbar.html
<div>
    <!-- it uses the name inside urls index, about and contact are url name-->
    {% url 'public:index' as index_url%}
    <span>{% if request.path  == index_url %}Home{%else%}<a href="{% url 'public:index' %}">Home</a>{%endif%}</span>

    {% url 'public:about' as about_url%}
    <span>{% if request.path  == about_url %}about{%else%}<a href="{% url 'public:about' %}">About</a>{%endif%}</span>

    {% url 'public:contact' as contact_url%}
    <span>{% if request.path  == contact_url %}contact{%else%}<a href="{% url 'public:contact' %}">Contact</a>{%endif%}</span>
    <!-- user can be accessed directly -->
    <span style="float: right;">
        {% if user.is_authenticated %}
        {% url 'accounts:profile' as profile_url%}
            <span>Hi {% if request.path  == profile_url %}{{user.username}}! {%else%}<a style =" padding:4px;"href="{% url 'accounts:profile' %}">{{user.username}}</a>{%endif%}</span>
            <span><a href="{% url 'accounts:logout' %}">Logout</a></span>
        {% else %}
            <span><a href="{% url 'accounts:login' %}">Login</a></span>
        {%endif%}
    </span>
</div>